/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenges;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testShift(){
        int [] input = new int[] {5,6,7,8};
        int [] inputOdd = new int[] {5,6,10,7,8};
        int insert = 1;
        int[] trueOutput = Library.shiftArray(input, insert);
        int[] trueOutputOdd = Library.shiftArray(inputOdd, insert);
        int[] expectOutput = new int[]{5,6,1,7,8};
        int[] expectOutputOdd = new int[]{5,6,10,1,7,8};
        assertArrayEquals(expectOutput, trueOutput);
        assertArrayEquals(expectOutputOdd, trueOutputOdd);
    }
}
