/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenges;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testShift(){
        int [] input = new int[] {5,6,7,8};
        int [] inputOdd = new int[] {5,6,10,7,8};
        int insert = 1;
        int[] trueOutput = Library.shiftArray(input, insert);
        int[] trueOutputOdd = Library.shiftArray(inputOdd, insert);
        int[] expectOutput = new int[]{5,6,1,7,8};
        int[] expectOutputOdd = new int[]{5,6,10,1,7,8};
        assertArrayEquals(expectOutput, trueOutput);
        assertArrayEquals(expectOutputOdd, trueOutputOdd);
    }
    @Test
    public void testBinarySearch(){
        int inputArray [] = {1,2,3,4,5,6,7};
        int inputSearch = 5;
        int expectOutput = 4;
        int trueOutput = BinarySearch.BinarySearch(inputArray,inputSearch);
        assertEquals(trueOutput,expectOutput);
        inputArray [] = {1,2,3,4,5,6,7, 0};
        inputSearch = 23;
        expectOutput = -1;
        trueOutput = BinarySearch.BinarySearch(inputArray,inputSearch);
        assertEquals(trueOutput,expectOutput);
    }
}
